[package]
name = "aptos-telemetry-service"
description = "Web service to receive telemetry from nodes and ingest it to backends"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-types = { path = "../../types" }

anyhow = "1.0.57"
base64 = "0.13.0"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
chrono = "0.4"
clap = "3.1.8"
debug-ignore = { version = "1.0.3", features = ["serde"] }
flate2 = "1.0.24"
futures = "0.3.21"
gcp-bigquery-client = "0.13"
hex = "0.4.3"
jsonwebtoken = "8.1"
once_cell = "1.10.0"
prometheus = { version = "0.13.1", default-features = false }
rand = "0.7.3"
rand_core = { version = "0.5.1", default-features = false }
reqwest = { version = "0.11.10", features = ["json"] }
reqwest-middleware = { version = "0.1.6" }
reqwest-retry = { version = "0.1.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_yaml = "0.8.24"
thiserror = "1.0"
tokio = { version = "1.21.0", features = ["full"] }
tracing = "0.1.34"
url = "2.2.2"
warp = { version = "0.3.2", features = ["tls"] }

[dev-dependencies]
httpmock = "0.6"
